In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)

In [4]:
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
df=dataset.copy()

In [7]:
df

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-length  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [37]:
x=df.drop('Class',axis=1)
y=df['Class']

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [40]:
from sklearn.decomposition import PCA

In [55]:
pca = PCA(n_components=2,random_state=0)

In [56]:
x_feature_train=pca.fit_transform(x_train)

In [57]:
x_feature_test=pca.transform(x_test)

In [58]:
x_feature_train

array([[-3.17186539,  0.13959658],
       [-2.34476845,  1.34616311],
       [ 0.97116618,  0.48717842],
       [-2.56806407,  0.02449273],
       [-2.95205699, -0.33412307],
       [ 1.57209503, -0.35611709],
       [ 0.97622042,  0.33649622],
       [-2.51864264,  0.37833149],
       [-2.684914  ,  0.33588705],
       [-2.6058472 ,  0.82262514],
       [ 1.46097067, -0.55797691],
       [ 0.8509521 ,  0.20941679],
       [ 1.26422963,  0.42801328],
       [-2.58126939,  0.81859379],
       [-2.46391446,  0.65577665],
       [-0.14343496, -0.66232798],
       [ 1.48934477, -0.12209998],
       [ 1.94978452,  0.06935085],
       [ 0.94380209,  0.34845584],
       [ 2.95905972,  0.80156812],
       [ 0.42157322, -0.27645378],
       [ 3.44052325,  0.5777973 ],
       [ 0.70579945, -0.33723213],
       [-2.64038049,  0.32925888],
       [ 3.54373422,  0.48976056],
       [ 0.28181351, -0.31405858],
       [-2.59584698,  0.3226307 ],
       [-2.72642204,  0.27194487],
       [-2.16579678,

In [59]:
x_feature_test

array([[ 0.96720208, -0.16157188],
       [-2.15737838,  0.88440307],
       [ 3.83957063,  0.28573647],
       [ 0.85817936, -0.14571871],
       [ 1.37602531,  0.26730116],
       [-2.36676774,  0.42126774],
       [-0.12910987, -0.24065349],
       [ 1.96485379,  0.42627823],
       [ 0.99016993, -0.52235194],
       [ 0.181628  , -0.2965922 ],
       [ 1.705385  ,  0.25948898],
       [-2.74099962, -0.22401822],
       [-2.58237434,  0.61042226],
       [-2.62784648, -0.10227022],
       [-2.54464927,  0.52206903],
       [ 1.13896131,  0.30093385],
       [ 2.39447036, -0.02116663],
       [ 0.09120353, -0.56579596],
       [ 0.68752508, -0.4000529 ],
       [ 2.20411289, -0.19861542],
       [-2.58684345, -0.18690522],
       [ 1.33578853, -0.09961863],
       [-2.42477388,  0.14010435],
       [ 2.16841659, -0.19037403],
       [ 3.27241756,  1.39953247],
       [ 1.98732996,  0.20453387],
       [ 2.36650633, -0.21948355],
       [ 2.60663268,  0.29710975],
       [-2.66960703,

In [60]:
pca.explained_variance_ratio_

array([0.9195717 , 0.05707944])

In [61]:
pca.singular_values_

array([22.22153965,  5.53632026])

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [64]:
clf.fit(x_feature_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [65]:
y_predict=clf.predict(x_feature_test)

In [66]:
from sklearn.metrics import accuracy_score

In [67]:
accuracy_score(y_test, y_predict)

0.9333333333333333